Detekt 1.8.0, ktlint through detekt

diff --git a/scripts/pre-push b/scripts/pre-push
--- a/scripts/pre-push
+++ b/scripts/pre-push
@@ -1,6 +1,15 @@
-#!/bin/bash
-
-# Copy to .git/hooks in the project root
-# E.g. cp pre-push ../.git/hooks/ && chmod +x ../.git/hooks/pre-push
-
-./gradlew ktlintCheck detekt
+#!/usr/bin/env bash
+echo "Running detekt check..."
+OUTPUT="/tmp/detekt-$(date +%s)"
+./gradlew detektAll > $OUTPUT
+EXIT_CODE=$?
+if [ $EXIT_CODE -ne 0 ]; then
+  cat $OUTPUT
+  rm $OUTPUT
+  echo "***********************************************"
+  echo "                 Detekt failed                 "
+  echo " Please fix the above issues before committing "
+  echo "***********************************************"
+  exit $EXIT_CODE
+fi
+rm $OUTPUT
